# Generated by Django 4.2.6 on 2023-10-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoracao', '0002_asset_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='value',
        ),
    ]
