# Generated by Django 4.2.6 on 2023-10-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoracao', '0007_alter_monitor_interval_alter_monitor_lower_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Ativo'),
        ),
    ]
