# Generated by Django 4.2.6 on 2023-10-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='row',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
