# Generated by Django 4.2.6 on 2023-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoracao', '0004_quotation_delete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
