# Generated by Django 4.2.6 on 2023-10-17 01:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoracao', '0008_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoracao.asset', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='interval',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Intervalo'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='lower_limit',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Limite inferior'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='upper_limit',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Limite superior'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoracao.asset', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='recording_date',
            field=models.DateTimeField(verbose_name='Momento do registro'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='trade_date',
            field=models.DateTimeField(verbose_name='Horário da negociação'),
        ),
    ]
